<div style="background-color: #002147; padding: 25px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    Optimization Methods in ML LAB <br> 
    </div>
<!-- Chahat | Student at Ambala College of Engineering | All rights reserved -->

Optimization is the engine that powers machine learning. Whether we are adjusting weights in a neural network or finding the best hyperplane for a support vector machine, we are essentially solving an optimization problem. This notebook explores a spectrum of techniques used to minimize loss functions and maximize model efficiency.

### The programs included in this lab cover three primary domains of optimization:

#### Linear & Convex Optimization: 
Solving problems with specific constraints using structured methods (Linear Programming, SOCP) and exploring the mathematical foundations of optimality (KKT Conditions).

#### Matrix Factorization: 
Utilizing EVD and SVD to understand data dimensionality, which is crucial for Principal Component Analysis (PCA) and feature compression.

#### Iterative & Stochastic Algorithms: 
Implementing the "bread and butter" of modern ML training, ranging from classic Gradient Descent and SGD to the Frank-Wolfe algorithm for constrained optimization.

#### Global & Nature-Inspired Heuristics: 
Exploring non-gradient-based approaches like Genetic Algorithms and Particle Swarm Optimization (PSO) for complex, non-convex landscapes where traditional calculus might fail.

### Mathematical Foundations
Most of the tasks within this notebook objective seek to solve:$$\min_{x \in \mathcal{C}} f(x)$$
Where:
* $f(x)$ is the Objective Function (the cost or loss).
* $\mathcal{C}$ represents the Feasible Set defined by constraints (like those in your Linear Programming task).
* For deep learning tasks, we specifically focus on Stochastic Gradient Descent, which approximates the gradient using subsets of data to handle massive datasets efficiently.

## Topics Covered
1. [Program-1](#Program-1)
2. [Program-2](#Program-2)
3. [Program-3](#Program-3)
4. [Program-4](#Program-4) 
5. [Program-5](#Program-5)
6. [Program-6](#Program-6)
7. [Program-7](#Program-7)
8. [Program-8](#Program-8)
9. [Program-9](#Program-9)
10. [Program-10](#Program-10)


# Program-1

<div style="background-color: #002146; padding: 10px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    Write a python program to solve the linear problem: <br> 
    </div>
<!-- Chahat | Student at Ambala College of Engineering | All rights reserved -->

#### Minimize:  Z = 3x + 5y 
#### Subject to the constraints: 
#### 2x + 3y >= 12 
#### -x + y <= 3 
#### x >= 4 
#### y <= 3 
#### x, y >= 0 

Description: This Python script utilizes the scipy.optimize.linprog library to find the minimum value of a linear objective function subject to specific linear constraints. It mathematically reformulates inequality constraints into a standard matrix format and applies the HiGHS solver to identify the optimal coordinates for x and y within the feasible region.

In [18]:
import numpy as np
from scipy.optimize import linprog

# Objective function coefficients (minimize 3x + 5y)
c = [3, 5]

# Inequality constraints: Ax <= b
# 1. -2x - 3y <= -12  (from 2x + 3y >= 12)
# 2. -x + y <= 3
A_ub = [[-2, -3],
        [-1, 1]]
b_ub = [-12, 3]

# Bounds: x >= 4, 0 <= y <= 3
bounds = [(4, None), (0, 3)]

# Solve
result = linprog(c, A_ub=A_ub, b_ub=b_ub, bounds=bounds, method='highs')

print("Optimal solution:")
print(f"x = {result.x[0]:.2f}")
print(f"y = {result.x[1]:.2f}")
print(f"Minimum Z = {result.fun:.2f}")
print(f"Success: {result.success}")

Optimal solution:
x = 6.00
y = 0.00
Minimum Z = 18.00
Success: True


# Program-2

<div style="background-color: #002147; padding: 16px; text-align: center; color: white; font-size: 16px; font-family: 'Arial', sans-serif;">
    Write a program in python to find the EVD (Eigen Value Decomposition) of A, where A = [[1, 0, -1], [1, 2, 1], [2, 2, 3]] <br> 
    </div>
<!-- Chahat | Student at Ambala College of Engineering | All rights reserved -->

## Eigen Value Decomposition
### EVD -> A = V * lambda(D) * V^-1

### Steps to perform Eigen Value Decomposition
#### 1. Find the Eigenvalues:
#### 2. Find the Eigenvectors:
#### 3. Construct the Eigenvector Matrix V:
#### 4. Form the Diagonal Matrix Λ:
#### 5. Calculate the Inverse of V:

Description: This script performs Eigenvalue Decomposition (EVD) on a square matrix using NumPy to extract its characteristic eigenvalues and eigenvectors. It then attempts to reconstruct the original matrix by calculating the product V * Lambda * V^{-1} to verify the decomposition, utilizing modern Python matrix multiplication syntax.

In [17]:
import numpy as np

# Define matrix
A = np.array([[1, 0, -1], [2, 2, 1], [3, 2, 0]]) # Note: Changed last element to 0 for variety

eigenvalues, eigenvectors = np.linalg.eig(A)

# 1. Use a name other than 'lambda'
# 2. Create the diagonal matrix of eigenvalues
L = np.diag(eigenvalues)

v = eigenvectors
v_inv = np.linalg.inv(v)

# 3. Use @ for matrix multiplication
EVD = v * L * v_inv

print("Original Matrix A:\n", A)
print("\nReconstructed Matrix from EVD:\n", EVD)

Original Matrix A:
 [[ 1  0 -1]
 [ 2  2  1]
 [ 3  2  0]]

Reconstructed Matrix from EVD:
 [[5.00000000e-01+2.02072594e+00j 0.00000000e+00+0.00000000e+00j
  0.00000000e+00-0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 1.00000000e+00+1.73205081e+00j
  0.00000000e+00-0.00000000e+00j]
 [0.00000000e+00+0.00000000e+00j 0.00000000e+00-0.00000000e+00j
  1.27881149e-17+4.87820418e-34j]]


# Program-3

<div style="background-color: #002147; padding: 10px; text-align: center; color: white; font-size: 16px; font-family: 'Arial', sans-serif;">
    Write a program in python to find the SVD (Singular Value Decomposition) of A, UΣV T, where A=[[3, 2, 2], [2, 3, -2]] <br> 
    </div>
<!-- Chahat | Student at Ambala College of Engineering | All rights reserved -->

Description: This script implements Singular Value Decomposition (SVD) to factorize a non-square matrix into its unitary and diagonal components using NumPy. It demonstrates the reconstruction process by populating a matching 3 * 2 Sigma matrix with singular values and performing matrix multiplication to recover the original dataset.

In [8]:
import numpy as np

# Define matrix (3x2)
A = np.array([[1, 0], [2, 2], [3, 2]])

# SVD decomposition
U, S, VT = np.linalg.svd(A)
print("U: ", U)
print("\nS: ", S)
print("\nVT: ", VT)

# Create the Sigma matrix (3x2) to match A's dimensions
Sigma = np.zeros((3, 2))
print("\nSigma: ",Sigma)
# Fill the diagonal with the singular values
Sigma[:2, :2] = np.diag(S)
print("\nSigma after filling diagonals with SV: ",Sigma)
# Reconstruct the matrix
A_svd = U @ Sigma @ VT

print("\nOriginal Matrix A:\n", A)
print("\nReconstructed Matrix from SVD:\n", A_svd)

U:  [[-0.17326764  0.79790036 -0.57735027]
 [-0.60436816 -0.54900436 -0.57735027]
 [-0.77763581  0.248896    0.57735027]]

S:  [4.63036786 0.74812665]

VT:  [[-0.80229293 -0.59693053]
 [ 0.59693053 -0.80229293]]

Sigma:  [[0. 0.]
 [0. 0.]
 [0. 0.]]

Sigma after filling diagonals with SV:  [[4.63036786 0.        ]
 [0.         0.74812665]
 [0.         0.        ]]

Original Matrix A:
 [[1 0]
 [2 2]
 [3 2]]

Reconstructed Matrix from SVD:
 [[ 1.00000000e+00 -2.22044605e-16]
 [ 2.00000000e+00  2.00000000e+00]
 [ 3.00000000e+00  2.00000000e+00]]


# Program-4

<div style="background-color: #002147; padding: 10px; text-align: center; color: white; font-size: 30px; font-family: 'Arial', sans-serif;">
    Write a program to implement Second Order Cone Program (SOCP). <br> 
    </div>
<!-- Chahat | Student at Ambala College of Engineering | All rights reserved -->

Description: This script utilizes SciPy's minimize function to solve a Second-Order Cone Program (SOCP) by minimizing a quadratic objective function subject to a conic constraint. It defines the feasible region where the Euclidean norm of the sub-vector is bounded by the first variable, effectively finding the optimal point within a three-dimensional cone.

In [10]:
# Second Order Cone Program (SOCP) Implementation

import numpy as np
from scipy.optimize import minimize

def socp_objective(x):
    # Objective function to minimize
    return x[0]**2 + x[1]**2

def socp_constraint(x):
    # Second order cone constraint: ||x[1:]|| <= x[0]
    return x[0]**2 - np.sum(x[1:]**2)

# Initial guess
x0 = np.array([1.0, 0.0, 0.0])

# Constraints definition
constraints = {'type': 'ineq', 'fun': socp_constraint}

# Bounds for the variables
bounds = [(0, None), (None, None), (None, None)]

# Solve the SOCP
result = minimize(socp_objective, x0, bounds=bounds, constraints=constraints)

# Output the result
print("Optimal value:", result.fun)
print("Optimal solution:", result.x)


Optimal value: 2.3602761637986642e-07
Optimal solution: [ 4.85823210e-04 -1.85066495e-06  1.16506227e-07]


# Program-5

<div style="background-color: #002147; padding: 10px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    Write a program to demonstrate KKT conditions. <br> 
    </div>
<!-- Chahat | Student at Ambala College of Engineering | All rights reserved --> 

Description: This program solves a constrained optimization problem by minimizing a quadratic objective function subject to multiple inequality constraints using SciPy's minimize solver. It validates the Karush-Kuhn-Tucker (KKT) framework by finding an optimal solution where the gradients of the objective and active constraints balance within the feasible region.

In [11]:
# KKT Conditions Demonstration

import numpy as np
from scipy.optimize import minimize

# Objective function
def objective(x):
    return x[0]**2 + x[1]**2

# Constraints
def constraint1(x):
    return x[0] + x[1] - 1

def constraint2(x):
    return x[0] - 0.5

# Initial guess
x0 = [0.5, 0.5]

# Constraints in dictionary form
con1 = {'type': 'ineq', 'fun': constraint1}
con2 = {'type': 'ineq', 'fun': constraint2}
constraints = [con1, con2]

# Optimization
solution = minimize(objective, x0, constraints=constraints)

# Display results
print("Optimal value:", solution.fun)
print("Optimal solution:", solution.x)
print("KKT conditions satisfied:", solution.success)


Optimal value: 0.5
Optimal solution: [0.5 0.5]
KKT conditions satisfied: True


# Progrma-6

<div style="background-color: #002147; padding: 10px; text-align: center; color: white; font-size: 20px; font-family: 'Arial', sans-serif;">
    Write a program to implement gradient Descent algorithm for finding local minima. <br> 
    </div>
<!-- Chahat | Student at Ambala College of Engineering | All rights reserved --> 

Description: This program implements a fundamental Gradient Descent algorithm that iteratively updates a starting value by moving in the direction of the steepest descent. It utilizes a learning rate and convergence tolerance to efficiently locate the local minimum of a function based on its derivative.

In [12]:
# Gradient Descent Algorithm Implementation

import numpy as np

def gradient_descent(gradient, start, learning_rate=0.1, tolerance=1e-6, max_iterations=1000):
    x = start
    for _ in range(max_iterations):
        grad = gradient(x)
        x_new = x - learning_rate * grad
        if np.abs(x_new - x) < tolerance:
            break
        x = x_new
    return x

# Example usage
def example_gradient(x):
    return 2 * x  # Derivative of f(x) = x^2

initial_guess = 10.0
minimum = gradient_descent(example_gradient, initial_guess)
print(f"The local minimum occurs at: {minimum}")


The local minimum occurs at: 4.017345110647478e-06


# Program-7

<div style="background-color: #002147; padding: 10px; text-align: center; color: white; font-size: 28px; font-family: 'Arial', sans-serif;">
    Write a program to implement Frank-Wolfe algorithm. <br> 
    </div>
<!-- Chahat | Student at Ambala College of Engineering | All rights reserved -->

Description: This program implements the Frank-Wolfe (conditional gradient) algorithm, an iterative method used for constrained convex optimization. It finds the optimal solution by solving a linearized subproblem at each step to determine a descent direction and updating the current point through a convex combination of its previous state and the new direction.

In [13]:
# Frank-Wolfe Algorithm Implementation

import numpy as np

def frank_wolfe(f, grad_f, x0, num_iterations=100, step_size=1.0):
    x = x0
    trajectory = [x]

    for _ in range(num_iterations):
        # Compute the gradient at the current point
        grad = grad_f(x)
        
        # Solve the linearized problem to find the new direction
        s = linearized_problem(grad)
        
        # Update the current point using the step size
        x = (1 - step_size) * x + step_size * s
        trajectory.append(x)

    return x, trajectory

def linearized_problem(grad):
    # Placeholder for the linearized problem solution
    # Replace with actual implementation based on the specific problem
    return -grad  # Example: moving in the opposite direction of the gradient

# Example usage
if __name__ == "__main__":
    # Define a simple quadratic function and its gradient
    def f(x):
        return 0.5 * np.dot(x, x)

    def grad_f(x):
        return x

    # Initial point
    x0 = np.array([1.0, 1.0])
    
    # Run the Frank-Wolfe algorithm
    solution, trajectory = frank_wolfe(f, grad_f, x0)
    print("Optimal solution:", solution)
    print("Trajectory:", trajectory)


Optimal solution: [1. 1.]
Trajectory: [array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-1., -1.]), array([1., 1.]), array([-

# Program-8

<div style="background-color: #002147; padding: 10px; text-align: center; color: white; font-size: 25px; font-family: 'Arial', sans-serif;">
    Write a program to implement Stochastic Gradient Descent Algorithm. <br> 
    </div>
<!-- Chahat | Student at Ambala College of Engineering | All rights reserved -->

Description: This program implements Stochastic Gradient Descent (SGD) for linear regression by updating model weights based on individual, randomly selected data points rather than the entire dataset. This iterative approach allows for faster convergence on large datasets by calculating gradients locally and gradually minimizing the error across a specified number of iterations.

In [14]:
# Stochastic Gradient Descent Algorithm

import numpy as np

class StochasticGradientDescent:
    def __init__(self, learning_rate=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations

    def fit(self, X, y):
        self.theta = np.zeros(X.shape[1])
        m = len(y)

        for iteration in range(self.n_iterations):
            for i in range(m):
                random_index = np.random.randint(m)
                xi = X[random_index:random_index + 1]
                yi = y[random_index:random_index + 1]
                gradients = 2 * xi.T.dot(xi.dot(self.theta) - yi)
                self.theta -= self.learning_rate * gradients

    def predict(self, X):
        return X.dot(self.theta)

# Example usage
if __name__ == "__main__":
    # Sample data
    X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
    y = np.array([1, 2, 2, 3])

    # Create and fit the model
    model = StochasticGradientDescent(learning_rate=0.01, n_iterations=1000)
    model.fit(X, y)

    # Make predictions
    predictions = model.predict(X)
    print(predictions)


[1.00004288 1.99992712 2.00008576 2.99997   ]


# Program-9

<div style="background-color: #002147; padding: 10px; text-align: center; color: white; font-size: 20px; font-family: 'Arial', sans-serif;">
    Write a program to create target string starting from random string using Genetic Algorithm.  <br> 
    </div>
<!-- Chahat | Student at Ambala College of Engineering | All rights reserved -->

Description: This program demonstrates a Genetic Algorithm that evolves a population of random strings to match a specific target phrase through natural selection principles. It iteratively applies fitness evaluation, crossover, and mutation to improve the population's accuracy until the optimal "Hello, World!" sequence is successfully generated.

In [19]:
import random

# Target string
target = "Hello, World!"
target_length = len(target)

# Population size
population_size = 100

# Mutation rate
mutation_rate = 0.01

# Generate a random string
def random_string(length):
    characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ ,!"
    return ''.join(random.choice(characters) for _ in range(length))

# Fitness function
def fitness(string):
    return sum(1 for a, b in zip(string, target) if a == b)

# Create initial population
population = [random_string(target_length) for _ in range(population_size)]

# Main Genetic Algorithm loop
def genetic_algorithm():
    global population
    generation = 0
    while True:
        population = sorted(population, key=fitness, reverse=True)
        best_match = population[0]
        print(f"Generation: {generation}, Best Match: {best_match}, Fitness: {fitness(best_match)}")
        
        if best_match == target:
            break
        
        new_population = population[:2]  # Keep the best two
        while len(new_population) < population_size:
            parent1, parent2 = random.choices(population[:50], k=2)
            child = crossover(parent1, parent2)
            new_population.append(mutate(child))
        
        population = new_population
        generation += 1

# Crossover function
def crossover(parent1, parent2):
    crossover_point = random.randint(0, target_length - 1)
    return parent1[:crossover_point] + parent2[crossover_point:]

# Mutation function
def mutate(string):
    return ''.join(
        char if random.random() > mutation_rate else random.choice("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ ,!")
        for char in string
    )

# Run the Genetic Algorithm
genetic_algorithm()


Generation: 0, Best Match: ABmOKniWoYBLe, Fitness: 2
Generation: 1, Best Match: HaEFDPPWoYBLe, Fitness: 3
Generation: 2, Best Match: HaEFDPPWoYBLe, Fitness: 3
Generation: 3, Best Match: HavzN,HWoYBPL, Fitness: 4
Generation: 4, Best Match: HavzN,HWoYBPL, Fitness: 4
Generation: 5, Best Match: HAlbMOWWoroA!, Fitness: 6
Generation: 6, Best Match: HAlbMOWWoroA!, Fitness: 6
Generation: 7, Best Match: HAllKg WoroA!, Fitness: 8
Generation: 8, Best Match: HAllKg WoroA!, Fitness: 8
Generation: 9, Best Match: HAllKg WoroA!, Fitness: 8
Generation: 10, Best Match: HAllKg WoroA!, Fitness: 8
Generation: 11, Best Match: HAllK, WoroA!, Fitness: 9
Generation: 12, Best Match: HAllK, WoroA!, Fitness: 9
Generation: 13, Best Match: HAllK, WoroA!, Fitness: 9
Generation: 14, Best Match: HjllM, Wordd!, Fitness: 10
Generation: 15, Best Match: HjllM, Wordd!, Fitness: 10
Generation: 16, Best Match: HjllM, Wordd!, Fitness: 10
Generation: 17, Best Match: HjllM, Wordd!, Fitness: 10
Generation: 18, Best Match: HjllM,

# Program-10

<div style="background-color: #002147; padding: 10px; text-align: center; color: white; font-size: 25px; font-family: 'Arial', sans-serif;">
    Write a program to implement Particle Swarm optimization to find optimal solution. 
 <br> 
    </div>
<!-- Chahat | Student at Ambala College of Engineering | All rights reserved -->

Description: This script implements Particle Swarm Optimization (PSO), a heuristic search method inspired by the collective behavior of bird flocks to find the global minimum of a function. It simulates a population of "particles" that traverse the search space by adjusting their velocities based on both their personal best-known positions and the best position discovered by the entire swarm.

In [16]:
# Particle Swarm Optimization

import numpy as np

class Particle:
    def __init__(self, bounds):
        self.position = np.random.uniform(bounds[0], bounds[1], size=len(bounds))
        self.velocity = np.random.uniform(-1, 1, size=len(bounds))
        self.best_position = np.copy(self.position)
        self.best_value = float('inf')

def objective_function(x):
    return sum(x**2)

def particle_swarm_optimization(num_particles, bounds, num_iterations):
    swarm = [Particle(bounds) for _ in range(num_particles)]
    global_best_position = np.copy(swarm[0].best_position)
    global_best_value = float('inf')

    for _ in range(num_iterations):
        for particle in swarm:
            current_value = objective_function(particle.position)

            if current_value < particle.best_value:
                particle.best_value = current_value
                particle.best_position = np.copy(particle.position)

            if current_value < global_best_value:
                global_best_value = current_value
                global_best_position = np.copy(particle.position)

            inertia_weight = 0.5
            cognitive_component = 1.5 * np.random.rand() * (particle.best_position - particle.position)
            social_component = 1.5 * np.random.rand() * (global_best_position - particle.position)
            particle.velocity = inertia_weight * particle.velocity + cognitive_component + social_component
            particle.position += particle.velocity

    return global_best_position, global_best_value

# Parameters
num_particles = 30
bounds = [-10, 10]
num_iterations = 100

best_position, best_value = particle_swarm_optimization(num_particles, bounds, num_iterations)
print("Best Position:", best_position)
print("Best Value:", best_value)


Best Position: [1.52196586e-11 1.36786475e-11]
Best Value: 4.1874340594948905e-22
